service: allocations

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteIte
      Resource:
        - !GetAtt AllocationsTable.Arn

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  allocate:
    handler: src/api.allocate
    timeout: 10
    events:
      - http:
          path: /allocate
          method: post

resources:
  Resources:
    AllocationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Allocations
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
